### ISSUE TITLE
option to generate ns export

### ISSUE THREAD

**Issue by harrysolovay** [tjjfvi/moderate#4]
Let's say we're in a directory that contains a file `foo.ts`, and we want that directory's `mod.ts` to re-export the exports of `foo.ts` under the namespace `foo`.

`mod.ts`

```ts
// moderate --ns foo.ts=foo
```

... could generate the following:

```ts
// moderate foo.ts=foo

export * as foo from "./foo.ts"
```

**Comment by tjjfvi** [comment]
you can accomplish this today with
```ts
export * as foo from "./foo.ts"

// moderate --exclude foo.ts
```

**Comment by harrysolovay** [comment]
I suppose excluding the module + manually writing the ns re-export is better. Good thinking.
